spring.application.name=currency-service
server.port=8100

## CONFIGURAÇÕES DO BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/db_currency
spring.datasource.username=postgres
spring.datasource.password=admin

## NORMAL EM PRODUÇÃO.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:/db_migration

# Self Registration Pattern
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Ideal para mabiente containerizados
eureka.instance.prefer-ip-address=true
# Personalizar o Id de cada instância, para facilitar a identificação no Eureka Dashboard
eureka.instance.instance-id=${spring.application.name}:${server.port}
# Indicar que o Service Registry deve monitorar a saúde da aplicação, através actuator, e não somente Heartbeat
# Opcional - Valor Default = true
eureka.client.healthcheck.enabled=true
# Personalização de Metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=marcionavarro/microservices-java-2026

#Configuração minima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics
# Atenção: Cuidado a expor esses dados
# Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
# Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

# Personalização de informações do enpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Marcio Navarro

# Definir a utilização das Probes Liveness e Readiness + exibição de informações de componentes diversos
# Opcional: Padrão já é true
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
