spring.application.name=auth-service
server.port=8900

spring.datasource.url=jdbc:postgresql://localhost/db_user
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db_migration

#Self Registration Pattern
eureka.client.service-url.default-zone=http://localhost:8761/eureka
#Ideal para ambiente containerizados
eureka.instance.prefer-ip-address=true
#Personalizar o id de cada instância
eureka.instance.instance-id=${spring.application.name}:${server.port}
#Indicar que o Service Registry deve validar a saúde do serviço através do actuator, e não somente Heartbeat
# Opcional - Valor Default = TRUE
eureka.client.healthcheck.enabled=true

#Configuração mínima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics,circuit-breakers,circuit-breaker-events
#ATENÇÃO: Cuidado a expor esses dados
#Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
#Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

#Personalização de ifnormações do endpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Luciano Rodrigo Ferretto
#Personalização de Metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=luciano-ferretto/microservice-java-2026

#Definir a ulização das Probes Liveness e Readiness + exibição de de informações de componentes diversos
# Opcional: Padrão já é TRUE
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
