spring.application.name=product-service
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/db_product
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db_migration

# Self Registration Pattern
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
# Ideal para ambiente conteinerizados
eureka.instance.prefer-ip-address=true
# Personalizar o Id de cada instância, para facilitar a identificação no Eureka Dashboard
eureka.instance.instance-id=${spring.application.name}:${server.port}
# Indicar que o Service Registry deve monitorar a saúde da aplicação, através actuator, e não somente Heartbeat
# Opcional - Valor Default = true
eureka.client.healthcheck.enabled=true
# Personalização de metadatas para o Eureka Service Registry
eureka.instance.metadata-map.github.repo=marcionavarro/microservices-java-2026

#Configuração minima para atuação com o Service Registry de forma consciente
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
# Atenção: Cuidado a expor esses dados
# Exibir todas as informações de saúde da aplicação
management.endpoint.health.show-details=always
# Exibir informações no endpoint /actuator/info
management.info.env.enabled=true

# Personalização de informações do enpoint /actuator/info
info.app.name=${spring.application.name}
info.app.description=Microservice Java 2026
info.app.autor=Marcio Navarro

# Definir a utilização das Probes Liveness e Readiness + exibição de informações de componentes diversos
# Opcional: Padrão já é true
management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true

# RESILIENCE PATTERN - TIMEOUT
# Timeout para estabelecer conexão(1 segundo)
spring.cloud.openfeign.client.config.currency-service.connect-timeout=1000
# Timeout para processar e receber os dados (3 segundos)
spring.cloud.openfeign.client.config.currency-service.read-timeout=3000

# RESILIENCE PATTERN - RETRY
# Quantidade máxima de tentativas (primeira + 2 tentativas)
resilience4j.retry.instances.currency-service.max-attempts=3
# Tempo de espera inicial entre as tentativas
resilience4j.retry.instances.currency-service.wait-duration=500ms
# Ativa o recuo exponencial (Exponential Backoff)
resilience4j.retry.instances.currency-service.exponential-backoff-enabled=true
# Multiplicador do tempo de espera (Tentativa 1: 50ms -> Tentativa 2: 500ms x 2 = 1000ms)
resilience4j.retry.instances.currency-service.exponential-backoff-multiplier=2.0
# Ativa variação aleatório do tempo de espera (Jitter) para evitar picos de requisições
resilience4j.retry.instances.currency-service.enable-randomized-wait=true
# Fator do Jitter (Aplica uma flutuação aleatória de até 50% para mais ou menos do tempo de espera calculado)
resilience4j.retry.instances.currency-service.randomized-wait-factor=0.5

# Regra de Exceção: IGNORAR/RETENTAR (um ou outro)
# IGNORAR (Evita desperdício de recursos em falhas do cliente, como erros de validação)
# Ignora qualquer erro HTTP da familia 4xx (400, 401, 403, 404, etc)
resilience4j.retry.instances.currency-service.ignore-exceptions[0]=feign.FeignException\$FeignClientException

# RETENTAR (Foca apenas em falhas transitórias e instabilidades)]
# Retenta em caso de timeout controlado pelo OpenFeign (FeignException$ReadTimeout)
resilience4j.retry.instances.currency-service.retry-exceptions[0]=feign.RetryableException
# Retenta em caso de queda drástica do socket/rede pura
resilience4j.retry.instances.currency-service.retry-exceptions[1]=java.net.SocketException
# Retenta em caso de erros HTTP da família 5xx vindo do servidor (500, 502, 503, etc)
resilience4j.retry.instances.currency-service.retry-exceptions[2]=feign.FeignException\$FeignServerException

# RESILENCE PATTERN - CACHING
# Configura o tipo de cache. Para cache em memória o caffeine é considerado com melhor desempenho.
spring.cache.type=caffeine
# Configurações do cache: 500 objetos no máximo e com um tempo de expiração de 15 segundos
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=15s

# RESILIENCE PATTERN - CIRCUIT BREAKER
# Habilita o Circuit Breaker dp Resilience4j no OpenFeign
spring.cloud.openfeign.circuitbreaker.enabled=true
# Habilita o indicador de saúde para esta instancia de circuit breaker
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.register-health-indicator=true
# Numero de chamadas na janela deslizante para calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.slidingWindowSize=10
# Numero mínimo de cahamdas de calcular a taxa de falhas
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.minimumNumberOfCalls=5
# Percentual máximo de falhas permitido antes de abrir o circuito
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.failureRateThreshold=50
# Tempo que o circuito permanece aberto antes de ir para meio-aberto
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.waitDurationInOpenState=30s
# Numero de chamadas permitidas no estado meio-aberto para testar
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.permittedNumberOfCallsInHalfOpenState=3
# Ativa a transição automática de aberto para meio-aberto sem esperar chamada
resilience4j.circuitbreaker.instances.CurrencyClientgetCurrencyStringString.automaticTransitionFromOpenToHalfOpenEnabled=true

# Habilita o actuator monitorar a saúde em conjunto com o circuit breaker
management.health.circuitbreakers.enabled=true

# Faz o OpenFeign usar o nome do micro serviço como ID.... dessa forma sincroniza
# o retry com o circuit breaker
spring.cloud.openfeign.circuitbreaker.group.enabled=true